import type { Rel } from '@mikro-orm/core'
import { Entity, Index, ManyToOne, OptionalProps, PrimaryKey, Property } from '@mikro-orm/core'
import { User } from '../auth.entity'

/**
 * A phone allowed to sign its owner in with a fingerprint.
 *
 * One row per device rather than one secret per account: enrolling a second
 * phone must not silently sign the first one out, and each can be revoked on
 * its own from the profile.
 *
 * What is kept here is a hash. The secret itself is generated by the server,
 * handed to the device once, and lives in the phone's keystore afterwards —
 * a stolen database gives no one a way in.
 */
@Entity({ tableName: 'trusted_devices' })
export class TrustedDevice {
  [OptionalProps]?: 'id' | 'createdAt' | 'lastUsedAt' | 'revokedAt' | 'label'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @ManyToOne(() => User, { fieldName: 'user_id', deleteRule: 'cascade' })
  user!: Rel<User>

  /**
   * The device's own identifier, chosen by the app and stable across sign-ins.
   *
   * Indexed and not unique: the same phone may be trusted by two accounts, a
   * shop owner and a relative sharing it.
   */
  @Index()
  @Property({ fieldName: 'device_id', length: 128 })
  deviceId!: string

  @Property({ fieldName: 'key_hash', length: 64 })
  keyHash!: string

  /** What the owner reads in the list — "Pixel 9 Pro", not a serial number. */
  @Property({ length: 120 })
  label: string = 'Cet appareil'

  @Property({ fieldName: 'created_at' })
  createdAt: Date = new Date()

  @Property({ fieldName: 'last_used_at', nullable: true })
  lastUsedAt?: Date

  /** Kept rather than deleted: a revoked device is worth seeing in an audit. */
  @Property({ fieldName: 'revoked_at', nullable: true })
  revokedAt?: Date
}
