// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import { aiExampleControllerChatResponseTransformer } from "./transformers.gen";
import type {
  AdminControllerBroadcastNotificationData,
  AdminControllerBroadcastNotificationResponses,
  AdminControllerGetDashboardData,
  AdminControllerGetDashboardResponses,
  AdminControllerGetDisputesData,
  AdminControllerGetDisputesResponses,
  AdminControllerGetOrderByIdData,
  AdminControllerGetOrderByIdResponses,
  AdminControllerGetOrdersData,
  AdminControllerGetOrdersResponses,
  AdminControllerGetReportsData,
  AdminControllerGetReportsResponses,
  AdminControllerGetSettingsData,
  AdminControllerGetSettingsResponses,
  AdminControllerGetSupplierByIdData,
  AdminControllerGetSupplierByIdResponses,
  AdminControllerGetSuppliersData,
  AdminControllerGetSuppliersResponses,
  AdminControllerGetTransactionsData,
  AdminControllerGetTransactionsResponses,
  AdminControllerGetUsersData,
  AdminControllerGetUsersResponses,
  AdminControllerGetValidationsData,
  AdminControllerGetValidationsResponses,
  AdminControllerResolveDisputeData,
  AdminControllerResolveDisputeResponses,
  AdminControllerResolveReportData,
  AdminControllerResolveReportResponses,
  AdminControllerSuspendSupplierData,
  AdminControllerSuspendSupplierResponses,
  AdminControllerUpdateCommissionsData,
  AdminControllerUpdateCommissionsResponses,
  AdminControllerValidateSupplierData,
  AdminControllerValidateSupplierResponses,
  AiExampleControllerChatData,
  AiExampleControllerChatResponses,
  AiExampleControllerGenerateObjectData,
  AiExampleControllerGenerateObjectResponses,
  AiExampleControllerGenerateTextData,
  AiExampleControllerGenerateTextResponses,
  AiExampleControllerStreamChatData,
  AiExampleControllerStreamChatResponses,
  AiExampleControllerStreamObjectData,
  AiExampleControllerStreamObjectResponses,
  AiExampleControllerStreamTextData,
  AiExampleControllerStreamTextResponses,
  AiExampleUseCasesControllerUseCase1SingleGenerationData,
  AiExampleUseCasesControllerUseCase1SingleGenerationResponses,
  AiExampleUseCasesControllerUseCase2GroupedCallsData,
  AiExampleUseCasesControllerUseCase2GroupedCallsResponses,
  AiExampleUseCasesControllerUseCase3LogicalUnitsData,
  AiExampleUseCasesControllerUseCase3LogicalUnitsResponses,
  AiExampleUseCasesControllerUseCase4ChatSessionData,
  AiExampleUseCasesControllerUseCase4ChatSessionResponses,
  AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedData,
  AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponses,
  AppControllerGetHelloData,
  AppControllerGetHelloResponses,
  CategoriesControllerCreateData,
  CategoriesControllerCreateResponses,
  CategoriesControllerFindByIdData,
  CategoriesControllerFindByIdResponses,
  CategoriesControllerRemoveData,
  CategoriesControllerRemoveResponses,
  CategoriesControllerUpdateData,
  CategoriesControllerUpdateResponses,
  ChatControllerCreateConversationData,
  ChatControllerCreateConversationResponses,
  ChatControllerGetConversationsData,
  ChatControllerGetConversationsResponses,
  ChatControllerGetMessagesData,
  ChatControllerGetMessagesResponses,
  ChatControllerGetQuickRepliesData,
  ChatControllerGetQuickRepliesResponses,
  ChatControllerShareWhatsAppData,
  ChatControllerShareWhatsAppResponses,
  CommentsControllerCreateCommentData,
  CommentsControllerCreateCommentResponses,
  CommentsControllerDeleteCommentData,
  CommentsControllerDeleteCommentResponses,
  CommentsControllerGetCommentCountData,
  CommentsControllerGetCommentCountResponses,
  CommentsControllerGetCommentRepliesData,
  CommentsControllerGetCommentRepliesResponses,
  CommentsControllerGetCommentsData,
  CommentsControllerGetCommentsResponses,
  CommunityControllerCreatePublicationData,
  CommunityControllerCreatePublicationResponses,
  CommunityControllerGetGroupsData,
  CommunityControllerGetGroupsResponses,
  CommunityControllerGetPublicationsData,
  CommunityControllerGetPublicationsResponses,
  CommunityControllerGetShareUrlData,
  CommunityControllerGetShareUrlResponses,
  CommunityControllerJoinGroupData,
  CommunityControllerJoinGroupResponses,
  CommunityControllerLeaveGroupData,
  CommunityControllerLeaveGroupResponses,
  CommunityControllerReportPublicationData,
  CommunityControllerReportPublicationResponses,
  MediaControllerCompleteUploadData,
  MediaControllerCompleteUploadResponses,
  MediaControllerDeleteMediaData,
  MediaControllerDeleteMediaResponses,
  MediaControllerFindByEntityData,
  MediaControllerFindByEntityResponses,
  MediaControllerFindByIdData,
  MediaControllerFindByIdResponses,
  MediaControllerGetDownloadUrlData,
  MediaControllerGetDownloadUrlResponses,
  MediaControllerInitiateUploadData,
  MediaControllerInitiateUploadResponses,
  NotificationsControllerGetAllData,
  NotificationsControllerGetAllResponses,
  NotificationsControllerGetUnreadCountData,
  NotificationsControllerGetUnreadCountResponses,
  NotificationsControllerGetUnreadData,
  NotificationsControllerGetUnreadResponses,
  NotificationsControllerMarkAllAsReadData,
  NotificationsControllerMarkAllAsReadResponses,
  NotificationsControllerMarkAsReadData,
  NotificationsControllerMarkAsReadResponses,
  NotificationsControllerRegisterTokenData,
  NotificationsControllerRegisterTokenResponses,
  NotificationsControllerSendTestNotificationData,
  NotificationsControllerSendTestNotificationResponses,
  NotificationsControllerUnregisterTokenData,
  NotificationsControllerUnregisterTokenResponses,
  OrdersControllerAcceptData,
  OrdersControllerAcceptResponses,
  OrdersControllerConfirmDeliveryData,
  OrdersControllerConfirmDeliveryResponses,
  OrdersControllerCreateData,
  OrdersControllerCreateDisputeData,
  OrdersControllerCreateDisputeResponses,
  OrdersControllerCreateResponses,
  OrdersControllerFindAllData,
  OrdersControllerFindAllResponses,
  OrdersControllerFindByIdData,
  OrdersControllerFindByIdResponses,
  OrdersControllerRejectData,
  OrdersControllerRejectResponses,
  OrdersControllerUpdateStatusData,
  OrdersControllerUpdateStatusResponses,
  OtpAuthControllerGetChatTokenData,
  OtpAuthControllerGetChatTokenResponses,
  OtpAuthControllerGetSessionData,
  OtpAuthControllerGetSessionResponses,
  OtpAuthControllerLoginWithPhoneData,
  OtpAuthControllerLoginWithPhoneResponses,
  OtpAuthControllerRegisterWithEmailData,
  OtpAuthControllerRegisterWithEmailResponses,
  OtpAuthControllerRegisterWithTokenData,
  OtpAuthControllerRegisterWithTokenResponses,
  OtpAuthControllerRequestEmailOtpData,
  OtpAuthControllerRequestEmailOtpResponses,
  OtpAuthControllerRequestOtpData,
  OtpAuthControllerRequestOtpResponses,
  OtpAuthControllerRequestPasswordResetData,
  OtpAuthControllerRequestPasswordResetResponses,
  OtpAuthControllerResetPasswordData,
  OtpAuthControllerResetPasswordResponses,
  OtpAuthControllerVerifyOtpData,
  OtpAuthControllerVerifyOtpResponses,
  OtpAuthControllerVerifyPasswordResetData,
  OtpAuthControllerVerifyPasswordResetResponses,
  PaymentMethodAdminControllerCreateData,
  PaymentMethodAdminControllerCreateResponses,
  PaymentMethodAdminControllerGetOneData,
  PaymentMethodAdminControllerGetOneResponses,
  PaymentMethodAdminControllerListData,
  PaymentMethodAdminControllerListResponses,
  PaymentMethodAdminControllerRemoveData,
  PaymentMethodAdminControllerRemoveResponses,
  PaymentMethodAdminControllerToggleActiveData,
  PaymentMethodAdminControllerToggleActiveResponses,
  PaymentMethodAdminControllerUpdateData,
  PaymentMethodAdminControllerUpdateResponses,
  PaymentMethodPublicControllerGetAvailableData,
  PaymentMethodPublicControllerGetAvailableResponses,
  PaymentsControllerGetPaymentInfoData,
  PaymentsControllerGetPaymentInfoResponses,
  PaymentsControllerGetPaymentStatusData,
  PaymentsControllerGetPaymentStatusResponses,
  PaymentsControllerInitiateCheckoutPaymentData,
  PaymentsControllerInitiateCheckoutPaymentResponses,
  PaymentsControllerInitiateNoRedirectPaymentData,
  PaymentsControllerInitiateNoRedirectPaymentResponses,
  PaymentsControllerVerifyCheckoutPaymentData,
  PaymentsControllerVerifyCheckoutPaymentResponses,
  PaymentsWebhookControllerHandleFedaPayWebhookData,
  PaymentsWebhookControllerHandleFedaPayWebhookResponses,
  PaymentsWebhookControllerHandlePawerPayerWebhookData,
  PaymentsWebhookControllerHandlePawerPayerWebhookResponses,
  PaymentsWebhookControllerHandleStripeWebhookData,
  PaymentsWebhookControllerHandleStripeWebhookResponses,
  PostControllerCreatePostData,
  PostControllerCreatePostResponses,
  PostControllerGetUserPostData,
  PostControllerGetUserPostResponses,
  PostControllerGetUserPostsData,
  PostControllerGetUserPostsResponses,
  PostControllerPublishPostData,
  PostControllerPublishPostResponses,
  PostControllerUnpublishPostData,
  PostControllerUnpublishPostResponses,
  PostControllerUpdatePostData,
  PostControllerUpdatePostResponses,
  ProductsControllerCreateData,
  ProductsControllerCreateResponses,
  ProductsControllerFindByIdData,
  ProductsControllerFindByIdResponses,
  ProductsControllerFindBySupplierData,
  ProductsControllerFindBySupplierResponses,
  ProductsControllerSetPromotionData,
  ProductsControllerSetPromotionResponses,
  ProductsControllerSoftDeleteData,
  ProductsControllerSoftDeleteResponses,
  ProductsControllerSubscribeToStockAlertData,
  ProductsControllerSubscribeToStockAlertResponses,
  ProductsControllerUpdateData,
  ProductsControllerUpdateResponses,
  ProductsControllerUpdateStockData,
  ProductsControllerUpdateStockResponses,
  PublicPostControllerGetPostData,
  PublicPostControllerGetPostResponses,
  PublicPostControllerGetPostsData,
  PublicPostControllerGetPostsResponses,
  PublicPostControllerGetRandomPostData,
  PublicPostControllerGetRandomPostResponses,
  RatingsControllerCreateReviewData,
  RatingsControllerCreateReviewResponses,
  RatingsControllerGetSupplierBadgesData,
  RatingsControllerGetSupplierBadgesResponses,
  RatingsControllerGetSupplierReviewsData,
  RatingsControllerGetSupplierReviewsResponses,
  RatingsControllerReportReviewData,
  RatingsControllerReportReviewResponses,
  RolesControllerAssignRoleData,
  RolesControllerAssignRoleResponses,
  RolesControllerCreateData,
  RolesControllerCreateResponses,
  RolesControllerDeleteData,
  RolesControllerDeleteResponses,
  RolesControllerFindAllData,
  RolesControllerFindAllResponses,
  RolesControllerGetAllPermissionsData,
  RolesControllerGetAllPermissionsResponses,
  RolesControllerUpdateData,
  RolesControllerUpdateResponses,
  SearchControllerAutocompleteData,
  SearchControllerAutocompleteResponses,
  SearchControllerGetCategoriesData,
  SearchControllerGetCategoriesResponses,
  SearchControllerSearchProductsData,
  SearchControllerSearchProductsResponses,
  SubscriptionsControllerCancelSubscriptionData,
  SubscriptionsControllerCancelSubscriptionResponses,
  SubscriptionsControllerGetCurrentSubscriptionData,
  SubscriptionsControllerGetCurrentSubscriptionResponses,
  SubscriptionsControllerGetPlansData,
  SubscriptionsControllerGetPlansResponses,
  SubscriptionsControllerSubscribeData,
  SubscriptionsControllerSubscribeResponses,
  SubscriptionsControllerUpgradeSubscriptionData,
  SubscriptionsControllerUpgradeSubscriptionResponses,
  SuppliersControllerCreateDeliveryZoneData,
  SuppliersControllerCreateDeliveryZoneResponses,
  SuppliersControllerDeleteDeliveryZoneData,
  SuppliersControllerDeleteDeliveryZoneResponses,
  SuppliersControllerFindByIdData,
  SuppliersControllerFindByIdResponses,
  SuppliersControllerFindNearbyData,
  SuppliersControllerFindNearbyResponses,
  SuppliersControllerGetAnalyticsData,
  SuppliersControllerGetAnalyticsResponses,
  SuppliersControllerGetDashboardData,
  SuppliersControllerGetDashboardResponses,
  SuppliersControllerGetMyStatusData,
  SuppliersControllerGetMyStatusResponses,
  SuppliersControllerGetRatingsOverviewData,
  SuppliersControllerGetRatingsOverviewResponses,
  SuppliersControllerGetSettingsData,
  SuppliersControllerGetSettingsResponses,
  SuppliersControllerGetTopProductsData,
  SuppliersControllerGetTopProductsResponses,
  SuppliersControllerRegisterData,
  SuppliersControllerRegisterResponses,
  SuppliersControllerUpdateMeData,
  SuppliersControllerUpdateMeResponses,
  SuppliersControllerUpdateModeData,
  SuppliersControllerUpdateModeResponses,
  SuppliersControllerUpdateOpeningHoursData,
  SuppliersControllerUpdateOpeningHoursResponses,
  TrainingControllerCompleteModuleData,
  TrainingControllerCompleteModuleResponses,
  TrainingControllerGetDownloadUrlData,
  TrainingControllerGetDownloadUrlResponses,
  TrainingControllerGetModuleByIdData,
  TrainingControllerGetModuleByIdResponses,
  TrainingControllerGetModulesData,
  TrainingControllerGetModulesResponses,
  TrainingControllerGetMyProgressData,
  TrainingControllerGetMyProgressResponses,
  UsersControllerGetMeData,
  UsersControllerGetMeResponses,
  UsersControllerUpdateMeData,
  UsersControllerUpdateMeResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerGetHelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerGetHelloResponses,
    unknown,
    ThrowOnError
  >({ url: "/api", ...options });

export const otpAuthControllerGetSession = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OtpAuthControllerGetSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    OtpAuthControllerGetSessionResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/otp-auth/session", ...options });

export const otpAuthControllerGetChatToken = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OtpAuthControllerGetChatTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    OtpAuthControllerGetChatTokenResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/otp-auth/chat-token", ...options });

export const otpAuthControllerLoginWithPhone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerLoginWithPhoneData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerLoginWithPhoneResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerRequestOtp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerRequestOtpData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerRequestOtpResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/request",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerVerifyOtp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerVerifyOtpData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerVerifyOtpResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerRegisterWithToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerRegisterWithTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerRegisterWithTokenResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerRequestEmailOtp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerRequestEmailOtpData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerRequestEmailOtpResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/email/request",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerRegisterWithEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerRegisterWithEmailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerRegisterWithEmailResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/email/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerRequestPasswordReset = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerRequestPasswordResetData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerRequestPasswordResetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/password-reset/request",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerVerifyPasswordReset = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerVerifyPasswordResetData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerVerifyPasswordResetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/password-reset/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const otpAuthControllerResetPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OtpAuthControllerResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OtpAuthControllerResetPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/otp-auth/password-reset/reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const commentsControllerGetComments = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommentsControllerGetCommentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommentsControllerGetCommentsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/posts/{postSlug}/comments", ...options });

export const commentsControllerCreateComment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommentsControllerCreateCommentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommentsControllerCreateCommentResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/posts/{postSlug}/comments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const commentsControllerGetCommentCount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommentsControllerGetCommentCountData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommentsControllerGetCommentCountResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/posts/{postSlug}/comments/count", ...options });

export const commentsControllerGetCommentReplies = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommentsControllerGetCommentRepliesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommentsControllerGetCommentRepliesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/posts/{postSlug}/comments/{commentId}/replies", ...options });

export const commentsControllerDeleteComment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommentsControllerDeleteCommentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CommentsControllerDeleteCommentResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/posts/{postSlug}/comments/{commentId}", ...options });

export const postControllerGetUserPosts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostControllerGetUserPostsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PostControllerGetUserPostsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/posts", ...options });

export const postControllerCreatePost = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerCreatePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostControllerCreatePostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/posts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postControllerGetUserPost = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerGetUserPostData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PostControllerGetUserPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}", ...options });

export const postControllerUpdatePost = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerUpdatePostData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PostControllerUpdatePostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/posts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postControllerPublishPost = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerPublishPostData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PostControllerPublishPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/publish", ...options });

export const postControllerUnpublishPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostControllerUnpublishPostData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PostControllerUnpublishPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/unpublish", ...options });

export const publicPostControllerGetRandomPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PublicPostControllerGetRandomPostData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PublicPostControllerGetRandomPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/public/posts/random", ...options });

export const publicPostControllerGetPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PublicPostControllerGetPostData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PublicPostControllerGetPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/public/posts/{slug}", ...options });

export const publicPostControllerGetPosts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PublicPostControllerGetPostsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PublicPostControllerGetPostsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/public/posts", ...options });

export const aiExampleControllerGenerateText = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiExampleControllerGenerateTextData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerGenerateTextResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/generate-text",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleControllerGenerateObject = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiExampleControllerGenerateObjectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerGenerateObjectResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/generate-object",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleControllerChat = <ThrowOnError extends boolean = false>(
  options: Options<AiExampleControllerChatData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerChatResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: aiExampleControllerChatResponseTransformer,
    url: "/api/ai/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleControllerStreamText = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiExampleControllerStreamTextData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerStreamTextResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/stream-text",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleControllerStreamObject = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiExampleControllerStreamObjectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerStreamObjectResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/stream-object",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleControllerStreamChat = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiExampleControllerStreamChatData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AiExampleControllerStreamChatResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/stream-chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleUseCasesControllerUseCase1SingleGeneration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiExampleUseCasesControllerUseCase1SingleGenerationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AiExampleUseCasesControllerUseCase1SingleGenerationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/examples/use-case-1-single-generation",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleUseCasesControllerUseCase2GroupedCalls = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiExampleUseCasesControllerUseCase2GroupedCallsData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AiExampleUseCasesControllerUseCase2GroupedCallsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/examples/use-case-2-grouped-calls",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleUseCasesControllerUseCase3LogicalUnits = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiExampleUseCasesControllerUseCase3LogicalUnitsData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AiExampleUseCasesControllerUseCase3LogicalUnitsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/examples/use-case-3-logical-units",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleUseCasesControllerUseCase4ChatSession = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiExampleUseCasesControllerUseCase4ChatSessionData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AiExampleUseCasesControllerUseCase4ChatSessionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/examples/use-case-4-chat-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const aiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMerged = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/ai/examples/use-case-5-chat-session-with-turns-merged",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const searchControllerSearchProducts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchControllerSearchProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchControllerSearchProductsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/search/products", ...options });

export const searchControllerAutocomplete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchControllerAutocompleteData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchControllerAutocompleteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/search/autocomplete", ...options });

export const searchControllerGetCategories = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SearchControllerGetCategoriesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SearchControllerGetCategoriesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/search/categories", ...options });

export const suppliersControllerRegister = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SuppliersControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const suppliersControllerFindNearby = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerFindNearbyData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuppliersControllerFindNearbyResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/nearby", ...options });

export const suppliersControllerFindById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerFindByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuppliersControllerFindByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/{id}", ...options });

export const suppliersControllerUpdateMe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerUpdateMeData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    SuppliersControllerUpdateMeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const suppliersControllerGetMyStatus = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuppliersControllerGetMyStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuppliersControllerGetMyStatusResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/status", ...options });

export const suppliersControllerGetDashboard = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuppliersControllerGetDashboardData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuppliersControllerGetDashboardResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/dashboard", ...options });

export const suppliersControllerCreateDeliveryZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerCreateDeliveryZoneData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SuppliersControllerCreateDeliveryZoneResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/delivery-zones",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const suppliersControllerDeleteDeliveryZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerDeleteDeliveryZoneData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    SuppliersControllerDeleteDeliveryZoneResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/delivery-zones/{zoneId}", ...options });

export const suppliersControllerGetSettings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuppliersControllerGetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuppliersControllerGetSettingsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/settings", ...options });

export const suppliersControllerUpdateOpeningHours = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerUpdateOpeningHoursData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    SuppliersControllerUpdateOpeningHoursResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/settings/opening-hours",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const suppliersControllerUpdateMode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerUpdateModeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    SuppliersControllerUpdateModeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/settings/mode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const suppliersControllerGetAnalytics = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerGetAnalyticsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuppliersControllerGetAnalyticsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/analytics", ...options });

export const suppliersControllerGetTopProducts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuppliersControllerGetTopProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuppliersControllerGetTopProductsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/analytics/top-products", ...options });

export const suppliersControllerGetRatingsOverview = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuppliersControllerGetRatingsOverviewData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuppliersControllerGetRatingsOverviewResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/analytics/ratings", ...options });

export const usersControllerGetMe = <ThrowOnError extends boolean = false>(
  options?: Options<UsersControllerGetMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersControllerGetMeResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/users/me", ...options });

export const usersControllerUpdateMe = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerUpdateMeData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UsersControllerUpdateMeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mediaControllerInitiateUpload = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MediaControllerInitiateUploadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MediaControllerInitiateUploadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/media/upload",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mediaControllerCompleteUpload = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MediaControllerCompleteUploadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MediaControllerCompleteUploadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/media/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mediaControllerDeleteMedia = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MediaControllerDeleteMediaData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MediaControllerDeleteMediaResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/media/{id}", ...options });

export const mediaControllerFindById = <ThrowOnError extends boolean = false>(
  options: Options<MediaControllerFindByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MediaControllerFindByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/media/{id}", ...options });

export const mediaControllerGetDownloadUrl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MediaControllerGetDownloadUrlData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MediaControllerGetDownloadUrlResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/media/{id}/download", ...options });

export const mediaControllerFindByEntity = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MediaControllerFindByEntityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MediaControllerFindByEntityResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/media/entity/{entityType}/{entityId}", ...options });

export const notificationsControllerRegisterToken = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerRegisterTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    NotificationsControllerRegisterTokenResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/register-token", ...options });

export const notificationsControllerUnregisterToken = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerUnregisterTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    NotificationsControllerUnregisterTokenResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/unregister-token", ...options });

export const notificationsControllerGetUnread = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerGetUnreadData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    NotificationsControllerGetUnreadResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/unread", ...options });

export const notificationsControllerGetAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    NotificationsControllerGetAllResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications", ...options });

export const notificationsControllerGetUnreadCount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerGetUnreadCountData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    NotificationsControllerGetUnreadCountResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/count", ...options });

export const notificationsControllerMarkAsRead = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NotificationsControllerMarkAsReadData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    NotificationsControllerMarkAsReadResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/{id}/read", ...options });

export const notificationsControllerMarkAllAsRead = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsControllerMarkAllAsReadData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    NotificationsControllerMarkAllAsReadResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/read-all", ...options });

export const notificationsControllerSendTestNotification = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    NotificationsControllerSendTestNotificationData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    NotificationsControllerSendTestNotificationResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/notifications/test", ...options });

export const productsControllerFindBySupplier = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerFindBySupplierData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ProductsControllerFindBySupplierResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/{supplierId}/products", ...options });

export const productsControllerFindById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerFindByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ProductsControllerFindByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/products/{id}", ...options });

export const productsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ProductsControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const productsControllerSoftDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerSoftDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ProductsControllerSoftDeleteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/me/products/{id}", ...options });

export const productsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ProductsControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const productsControllerUpdateStock = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerUpdateStockData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ProductsControllerUpdateStockResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/products/{id}/stock",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const productsControllerSetPromotion = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerSetPromotionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ProductsControllerSetPromotionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/suppliers/me/products/{id}/promotion",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const productsControllerSubscribeToStockAlert = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProductsControllerSubscribeToStockAlertData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ProductsControllerSubscribeToStockAlertResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/products/{id}/stock-alert", ...options });

export const categoriesControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CategoriesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CategoriesControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/categories/{id}", ...options });

export const categoriesControllerFindById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CategoriesControllerFindByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CategoriesControllerFindByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/categories/{id}", ...options });

export const categoriesControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CategoriesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CategoriesControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/categories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const categoriesControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CategoriesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CategoriesControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ordersControllerFindAll = <ThrowOnError extends boolean = false>(
  options: Options<OrdersControllerFindAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    OrdersControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/orders", ...options });

export const ordersControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OrdersControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ordersControllerFindById = <ThrowOnError extends boolean = false>(
  options: Options<OrdersControllerFindByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    OrdersControllerFindByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/orders/{id}", ...options });

export const ordersControllerAccept = <ThrowOnError extends boolean = false>(
  options: Options<OrdersControllerAcceptData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    OrdersControllerAcceptResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/orders/{id}/accept", ...options });

export const ordersControllerReject = <ThrowOnError extends boolean = false>(
  options: Options<OrdersControllerRejectData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    OrdersControllerRejectResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/orders/{id}/reject",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ordersControllerUpdateStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrdersControllerUpdateStatusData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    OrdersControllerUpdateStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/orders/{id}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ordersControllerConfirmDelivery = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrdersControllerConfirmDeliveryData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    OrdersControllerConfirmDeliveryResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/orders/{id}/confirm-delivery", ...options });

export const ordersControllerCreateDispute = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrdersControllerCreateDisputeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OrdersControllerCreateDisputeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/orders/{id}/dispute",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentsControllerGetPaymentInfo = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerGetPaymentInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PaymentsControllerGetPaymentInfoResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payments/orders/{id}/info", ...options });

export const paymentsControllerInitiateNoRedirectPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PaymentsControllerInitiateNoRedirectPaymentData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    PaymentsControllerInitiateNoRedirectPaymentResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/payments/initiate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentsControllerInitiateCheckoutPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerInitiateCheckoutPaymentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PaymentsControllerInitiateCheckoutPaymentResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/payments/initiate-checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentsControllerVerifyCheckoutPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerVerifyCheckoutPaymentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PaymentsControllerVerifyCheckoutPaymentResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/payments/verify-checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentsControllerGetPaymentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerGetPaymentStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PaymentsControllerGetPaymentStatusResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payments/orders/{id}/status", ...options });

export const paymentsWebhookControllerHandleFedaPayWebhook = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentsWebhookControllerHandleFedaPayWebhookData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    PaymentsWebhookControllerHandleFedaPayWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payments/webhook/fedapay", ...options });

export const paymentsWebhookControllerHandleStripeWebhook = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PaymentsWebhookControllerHandleStripeWebhookData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    PaymentsWebhookControllerHandleStripeWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payments/webhook/stripe", ...options });

export const paymentsWebhookControllerHandlePawerPayerWebhook = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentsWebhookControllerHandlePawerPayerWebhookData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    PaymentsWebhookControllerHandlePawerPayerWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payments/webhook/pawerpayer", ...options });

export const paymentMethodAdminControllerList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentMethodAdminControllerListData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PaymentMethodAdminControllerListResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/payment-methods", ...options });

export const paymentMethodAdminControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentMethodAdminControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PaymentMethodAdminControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/payment-methods",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentMethodAdminControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentMethodAdminControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PaymentMethodAdminControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/payment-methods/{id}", ...options });

export const paymentMethodAdminControllerGetOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentMethodAdminControllerGetOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PaymentMethodAdminControllerGetOneResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/payment-methods/{id}", ...options });

export const paymentMethodAdminControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentMethodAdminControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PaymentMethodAdminControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/payment-methods/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const paymentMethodAdminControllerToggleActive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentMethodAdminControllerToggleActiveData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PaymentMethodAdminControllerToggleActiveResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/payment-methods/{id}/toggle", ...options });

export const paymentMethodPublicControllerGetAvailable = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentMethodPublicControllerGetAvailableData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    PaymentMethodPublicControllerGetAvailableResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/payment-methods/available", ...options });

export const chatControllerGetConversations = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ChatControllerGetConversationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ChatControllerGetConversationsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/chat/conversations", ...options });

export const chatControllerCreateConversation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatControllerCreateConversationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ChatControllerCreateConversationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/chat/conversations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const chatControllerGetMessages = <ThrowOnError extends boolean = false>(
  options: Options<ChatControllerGetMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ChatControllerGetMessagesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/chat/conversations/{id}/messages", ...options });

export const chatControllerShareWhatsApp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatControllerShareWhatsAppData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ChatControllerShareWhatsAppResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/chat/conversations/{id}/share-whatsapp", ...options });

export const chatControllerGetQuickReplies = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatControllerGetQuickRepliesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ChatControllerGetQuickRepliesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/chat/suppliers/{id}/quick-replies", ...options });

export const ratingsControllerCreateReview = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RatingsControllerCreateReviewData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RatingsControllerCreateReviewResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/reviews",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ratingsControllerGetSupplierReviews = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RatingsControllerGetSupplierReviewsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RatingsControllerGetSupplierReviewsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/{id}/reviews", ...options });

export const ratingsControllerGetSupplierBadges = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RatingsControllerGetSupplierBadgesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RatingsControllerGetSupplierBadgesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/{id}/badges", ...options });

export const ratingsControllerReportReview = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RatingsControllerReportReviewData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RatingsControllerReportReviewResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/reviews/{id}/report",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const communityControllerGetGroups = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerGetGroupsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommunityControllerGetGroupsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/groups", ...options });

export const communityControllerJoinGroup = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerJoinGroupData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommunityControllerJoinGroupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/groups/{id}/join", ...options });

export const communityControllerLeaveGroup = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerLeaveGroupData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CommunityControllerLeaveGroupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/groups/{id}/leave", ...options });

export const communityControllerGetPublications = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerGetPublicationsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommunityControllerGetPublicationsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/groups/{id}/publications", ...options });

export const communityControllerCreatePublication = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerCreatePublicationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommunityControllerCreatePublicationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/groups/{id}/publications",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const communityControllerReportPublication = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerReportPublicationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommunityControllerReportPublicationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/groups/publications/{id}/report",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const communityControllerGetShareUrl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CommunityControllerGetShareUrlData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CommunityControllerGetShareUrlResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/groups/publications/{id}/share-url", ...options });

export const trainingControllerGetModules = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TrainingControllerGetModulesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrainingControllerGetModulesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/training/modules", ...options });

export const trainingControllerGetModuleById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TrainingControllerGetModuleByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrainingControllerGetModuleByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/training/modules/{id}", ...options });

export const trainingControllerGetDownloadUrl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TrainingControllerGetDownloadUrlData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrainingControllerGetDownloadUrlResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/training/modules/{id}/download", ...options });

export const trainingControllerCompleteModule = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TrainingControllerCompleteModuleData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TrainingControllerCompleteModuleResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/training/modules/{id}/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const trainingControllerGetMyProgress = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TrainingControllerGetMyProgressData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TrainingControllerGetMyProgressResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/training/my-progress", ...options });

export const subscriptionsControllerGetPlans = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SubscriptionsControllerGetPlansData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SubscriptionsControllerGetPlansResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/subscriptions/plans", ...options });

export const subscriptionsControllerSubscribe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionsControllerSubscribeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SubscriptionsControllerSubscribeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/subscriptions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const subscriptionsControllerGetCurrentSubscription = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SubscriptionsControllerGetCurrentSubscriptionData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SubscriptionsControllerGetCurrentSubscriptionResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/subscriptions/me", ...options });

export const subscriptionsControllerCancelSubscription = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SubscriptionsControllerCancelSubscriptionData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).patch<
    SubscriptionsControllerCancelSubscriptionResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/subscriptions/me/cancel", ...options });

export const subscriptionsControllerUpgradeSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubscriptionsControllerUpgradeSubscriptionData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    SubscriptionsControllerUpgradeSubscriptionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/subscriptions/me/upgrade",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerGetDashboard = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminControllerGetDashboardData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AdminControllerGetDashboardResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/dashboard", ...options });

export const adminControllerGetValidations = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetValidationsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetValidationsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/validations", ...options });

export const adminControllerValidateSupplier = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerValidateSupplierData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    AdminControllerValidateSupplierResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/validations/{supplierId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerGetReports = <ThrowOnError extends boolean = false>(
  options: Options<AdminControllerGetReportsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetReportsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/reports", ...options });

export const adminControllerResolveReport = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerResolveReportData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    AdminControllerResolveReportResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/reports/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerGetDisputes = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetDisputesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetDisputesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/disputes", ...options });

export const adminControllerResolveDispute = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerResolveDisputeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    AdminControllerResolveDisputeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/disputes/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerSuspendSupplier = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerSuspendSupplierData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    AdminControllerSuspendSupplierResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/suppliers/{id}/suspend",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerGetTransactions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetTransactionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetTransactionsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/transactions", ...options });

export const adminControllerGetOrders = <ThrowOnError extends boolean = false>(
  options: Options<AdminControllerGetOrdersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetOrdersResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/orders", ...options });

export const adminControllerGetOrderById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetOrderByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetOrderByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/orders/{id}", ...options });

export const adminControllerGetSuppliers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetSuppliersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetSuppliersResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/suppliers", ...options });

export const adminControllerGetSupplierById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerGetSupplierByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetSupplierByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/suppliers/{id}", ...options });

export const adminControllerGetUsers = <ThrowOnError extends boolean = false>(
  options: Options<AdminControllerGetUsersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AdminControllerGetUsersResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/users", ...options });

export const adminControllerGetSettings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminControllerGetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AdminControllerGetSettingsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/settings", ...options });

export const adminControllerUpdateCommissions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerUpdateCommissionsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    AdminControllerUpdateCommissionsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/settings/commissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const adminControllerBroadcastNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminControllerBroadcastNotificationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AdminControllerBroadcastNotificationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/notifications/broadcast",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const rolesControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<RolesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RolesControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/roles", ...options });

export const rolesControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<RolesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RolesControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const rolesControllerGetAllPermissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RolesControllerGetAllPermissionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RolesControllerGetAllPermissionsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/roles/permissions", ...options });

export const rolesControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<RolesControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    RolesControllerDeleteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/roles/{id}", ...options });

export const rolesControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<RolesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    RolesControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/roles/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const rolesControllerAssignRole = <ThrowOnError extends boolean = false>(
  options: Options<RolesControllerAssignRoleData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RolesControllerAssignRoleResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/roles/assign",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
